"""Quantize a trained checkpoint to int8 and emit C header files.

Output is a self-contained pair of C arrays that can be #include'd
into the firmware build:

    weights.h  — int8 weight blob with per-tensor scale/zero-point
    arena.h    — the activation arena size required by the runtime

The codegen is intentionally minimal: PyTorch -> torch.quantization
post-training static quant -> raw int8 export -> C header dump.
We do not depend on TFLite-Micro tooling because the firmware uses
hand-written CMSIS-NN kernels for the four FEATHer operators
(DWConv1D, Linear, Softmax, AvgPool1D).

Usage (run from repo root, on Windows or WSL):

    python -m deployment.cortex_m3.qemu.codegen \
        --model FEATHer --data ETTh1 --pred_len 96 \
        --ckpt results/checkpoints/main/FEATHer_ETTh1_H96_L96_s2025.pth \
        --out  deployment/cortex_m3/qemu/firmware/gen/
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import torch

_ROOT = Path(__file__).resolve().parents[3]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from baselines import get_model  # noqa: E402


def _build_args(model_name, seq_len, pred_len, n_features):
    from baselines import get_method_defaults
    base = get_method_defaults(model_name)
    a = argparse.Namespace(
        model=model_name, seq_len=seq_len, pred_len=pred_len,
        label_len=seq_len // 2,
        enc_in=n_features, dec_in=n_features, c_out=n_features,
        features="M", freq="h", embed="timeF", use_norm=True,
        d_state=8, kernel_size=7, period=12, num_bands=3,
        use_topk_gate=False, topk=2, lambda_spec=0.01,
    )
    for k, v in base.items():
        setattr(a, k, v)
    return a


def quantize_and_dump(model, out_dir: Path):
    """int8 post-training quant + dump weights.h."""
    out_dir.mkdir(parents=True, exist_ok=True)
    model.eval()

    # Per-tensor symmetric quant (matches CMSIS-NN expectations).
    weights_h = out_dir / "weights.h"
    with weights_h.open("w") as f:
        f.write("// Auto-generated by deployment/cortex_m3/qemu/codegen.py\n")
        f.write("// Do not edit by hand.\n\n")
        f.write("#ifndef FEATHER_WEIGHTS_H\n#define FEATHER_WEIGHTS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        total_bytes = 0
        for name, p in model.named_parameters():
            t = p.detach().cpu().float()
            scale = t.abs().max().item() / 127.0 if t.numel() > 0 else 1.0
            q = (t / max(scale, 1e-12)).round().clamp(-128, 127).to(torch.int8)
            arr = q.flatten().tolist()
            cname = name.replace(".", "_").replace("-", "_")
            f.write(f"// {name}  shape={list(t.shape)}  scale={scale:.6e}\n")
            f.write(f"static const float {cname}_scale = {scale:.6e}f;\n")
            f.write(f"static const int8_t {cname}[{len(arr)}] = {{\n  ")
            for i, v in enumerate(arr):
                f.write(f"{v}, ")
                if (i + 1) % 16 == 0:
                    f.write("\n  ")
            f.write("\n};\n\n")
            total_bytes += len(arr)
        f.write(f"// Total weight bytes: {total_bytes}\n")
        f.write("#endif\n")
    print(f"  wrote {weights_h}  ({total_bytes} weight bytes)")


def emit_arena_header(arena_bytes: int, out_dir: Path):
    h = out_dir / "arena.h"
    with h.open("w") as f:
        f.write("// Auto-generated by deployment/cortex_m3/qemu/codegen.py\n\n")
        f.write("#ifndef FEATHER_ARENA_H\n#define FEATHER_ARENA_H\n\n")
        f.write(f"#define ARENA_BYTES {arena_bytes}\n")
        f.write("#endif\n")
    print(f"  wrote {h}  ({arena_bytes} arena bytes)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="FEATHer")
    ap.add_argument("--data", default="ETTh1")
    ap.add_argument("--pred_len", type=int, default=96)
    ap.add_argument("--seq_len", type=int, default=96)
    ap.add_argument("--n_features", type=int, default=7)
    ap.add_argument("--ckpt", default=None,
                    help="Optional .pth to load before quantization. "
                         "If omitted, the freshly-initialized weights "
                         "are quantized (smoke test).")
    ap.add_argument("--out", default="deployment/cortex_m3/qemu/firmware/gen")
    args = ap.parse_args()

    a = _build_args(args.model, args.seq_len, args.pred_len, args.n_features)
    model = get_model(args.model, a, args.n_features, args.seq_len, args.pred_len)

    if args.ckpt and os.path.exists(args.ckpt):
        sd = torch.load(args.ckpt, map_location="cpu", weights_only=False)
        if isinstance(sd, dict) and "model" in sd:
            sd = sd["model"]
        model.load_state_dict(sd, strict=False)
        print(f"  loaded checkpoint: {args.ckpt}")

    out_dir = Path(args.out)
    quantize_and_dump(model, out_dir)

    # Arena estimate piggybacks on the Layer-1 estimator.
    from deployment.cortex_m3.estimator import estimate_model
    est = estimate_model(
        model.eval(),
        model_name=args.model, data_name=args.data,
        seq_len=args.seq_len, pred_len=args.pred_len,
        n_features=args.n_features, bit_width=8,
    )
    emit_arena_header(est.activation_arena_bytes, out_dir)
    print(f"  estimator says peak RAM = "
          f"{est.peak_ram_bytes/1024:.1f} KB, "
          f"latency = {est.latency_ms:.2f} ms (Layer-1 prediction)")


if __name__ == "__main__":
    main()
